Resources:

  CancelUdnOrderDlqQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:custom.stage}-cancelUdnOrder-dlq

  CancelUdnOrderDlqQueueRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Dlq"
      Name: ${self:service}-${self:custom.stage}-cp-cancel-udn-order-dlq-rule
      State: "ENABLED"
      EventBusName: ${self:custom.eventBusArn}
      EventPattern:
        detail-type:
          - "Lambda Function Invocation Result - Failure"
        resources:
          - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:cp-cancel-udn-order-${self:custom.stage}-cancelUdnOrder:$LATEST"
        source:
          - "com.revolutionmortgage.encompass"
        detail:
          requestPayload:
            detail:
              retries:
              - numeric:
                - ">"
                - ${self:custom.replayMaxCount}


      RoleArn: !GetAtt CancelUdnOrderDlqQueueRuleRole.Arn
      Targets:
        - Arn: !GetAtt CancelUdnOrderDlqQueue.Arn
          Id: CancelUdnOrderDlqQueueRule2
          InputPath: "$.detail.requestPayload"

  CancelUdnOrderDlqQueueRulePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action: sqs:*
          Effect: Allow
          Resource: !GetAtt CancelUdnOrderDlqQueue.Arn
        Version: '2012-10-17'
      PolicyName: CancelUdnOrderDlqQueueRulePolicyName
      Roles:
      - Ref: CancelUdnOrderDlqQueueRuleRole

  CancelUdnOrderDlqQueueRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
            - sqs.amazonaws.com
        Version: '2012-10-17'

  CancelUdnOrderDlqQueuePolicy:
    DependsOn:
    - CancelUdnOrderDlqQueue
    - CancelUdnOrderDlqQueueRule
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: CancelUdnOrderDlqQueuePolicy
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
            - sqs.amazonaws.com
          Action: sqs:SendMessage
          Resource: !GetAtt CancelUdnOrderDlqQueue.Arn
      Queues:
      - Ref: CancelUdnOrderDlqQueue